### ISSUE TITLE
feature: search SGA with a short list of RA, Dec

### ISSUE THREAD

**Issue by stephjuneau** [moustakas/SGA#44]
In addition of searching around one RA, Dec location, it could be useful to have the option to search for a short list of galaxies by entering the list of RA, Dec values in a text box [ RA, Dec, [ID] ], or by uploading a temporary file. There are pros and cons, so this may not be a desired feature after all. Feel free to close this issue if you decide against it!

**Comment by moustakas** [comment]
With the SGA now available in DataLab, I don't think this is a feature I'm planning to implement.
