### ISSUE TITLE
Missing diameter values

### ISSUE THREAD

**Issue by dkirkby** [moustakas/SGA#46]
This looks great!

The galaxy diameter values are missing from the table on the home page and [clicking the diameter heading](https://sga.legacysurvey.org/?sort=diam#results) results in traceback.

**Comment by moustakas** [comment]
Thanks for the bug report, @dkirkby, this was fixed in https://github.com/moustakas/SGA/commit/fd528457e16c804eeeafaf2b673a6265acb4166c.
