### ISSUE TITLE
Integrated COG z magnitude is duplicate of r magnitude in web-page tables (via web portal)

### ISSUE THREAD

**Issue by perwin** [moustakas/SGA#53]
When searching via the web portal (https://sga.legacysurvey.org), the per-galaxy "Elliptical Isophote Analysis: Photometry" table in the results page seems to be missing the correct z-band Curve of Growth Photometry: Integrated value, with the r-band value duplicated in its place.

E.g., for NGC1079 (https://sga.legacysurvey.org/group/NGC1079?index=1), the g, r, and z values are "11.557 | 10.811 | 10.811". (From the full FITS "ELLIPSE" table, the corresponding values are 11.557453, 10.811194, 10.304616.)

I noticed this for about 45 galaxies I checked by hand, so it seems like a consistent bug.

**Comment by moustakas** [comment]
Thanks for the bug report @perwin, I'll try to diagnose this issue and will report back here.

**Comment by moustakas** [comment]
I'm embarrassed it took so long to address this issue, @perwin, but this is now fixed.

**Comment by moustakas** [comment]
Done in https://github.com/moustakas/SGA/commit/94524e76038d545eeb2ba93377a844c29adf48e7.
