### ISSUE TITLE
https://sga.legacysurvey.org  currently not accessible

### ISSUE THREAD

**Issue by JohanComparat** [moustakas/SGA#55]
Dear John,

I am trying to acces the SGA through LS website, I get the following error : " Your connection was interrupted. A network change was detected. ERR_NETWORK_CHANGED ".  (I am trying to connect from Munich Germany, in case it helps)
Maybe there is there maintenance ongoing ?

Thank you and best wishes

**Comment by moustakas** [comment]
Thanks for the report @JohanComparat! 

@dstndstn just restarted the web-server. Can you check now?

**Comment by JohanComparat** [comment]
It is now working. Thanks and cheers !
