### ISSUE TITLE
mistakes in SGA-2020

### ISSUE THREAD

**Issue by djschlegel** [moustakas/SGA#56]
This ticket can track galaxies in SGA-2020 used for DR9 that should be re-fit with different starting parameters:

https://www.legacysurvey.org/viewer?ra=55.11&dec=-28.68&layer=ls-dr9&zoom=14&sga

**Comment by moustakas** [comment]
PGC1168221: https://www.legacysurvey.org/viewer/?ra=139.0055415&dec=0.5240977&zoom=15&layer=ls-dr9&sga

**Comment by moustakas** [comment]
SDSSJ222743.82+070833.3 is Galactic cirrus
https://www.legacysurvey.org/viewer/?ra=336.9326010&dec=7.1425921&zoom=10&layer=ls-dr9&sga

**Comment by moustakas** [comment]
IC3049 group has a contaminating star:
https://www.legacysurvey.org/viewer?ra=183.3900&dec=14.4808&layer=ls-dr9&zoom=15&sga

**Comment by Snell1185** [comment]
PGC175015 is likely a foreground star.
https://sga.legacysurvey.org/group/PGC170565?index=1685
https://www.legacysurvey.org/viewer/?ra=1.208628&dec=-40.9016209&zoom=15&layer=ls-dr9&sga

**Comment by moustakas** [comment]
Additional related tickets:
* https://github.com/legacysurvey/legacypipe/issues/680
* https://github.com/legacysurvey/legacypipe/issues/598
* https://github.com/legacysurvey/legacypipe/issues/489
* https://github.com/legacysurvey/legacypipe/issues/626
* https://github.com/legacysurvey/legacypipe/issues/613
* https://github.com/legacysurvey/legacypipe/issues/600
* https://github.com/legacysurvey/legacypipe/issues/722

**Comment by moustakas** [comment]
UM461 is split into two; the secondary (SDSS) source is a compact HII region in this low-metallicity galaxy--https://www.legacysurvey.org/viewer?ra=177.8879&dec=-2.3733&layer=ls-dr10&zoom=16&sga

**Comment by moustakas** [comment]
ESO201-10 appears to be a globular cluster or something else (but not a galaxy)--
https://www.legacysurvey.org/viewer-desi/?ra=58.7621&dec=-49.6149&layer=ls-dr9&zoom=14&sga&sga-parent
https://ned.ipac.caltech.edu/byname?objname=ESO201-10&hconst=67.8&omegam=0.308&omegav=0.692&wmap=4&corr_z=1

**Comment by moustakas** [comment]
NGC0547 - crowded cluster field; SGA is totally wrong on one of the giant galaxies
https://www.legacysurvey.org/viewer-desi/?ra=21.5026&dec=-1.3447&layer=ls-dr9&zoom=14&sga&sga-parent

**Comment by moustakas** [comment]
PGC087438 is a crowded cluster that's not handled correctly--
https://www.legacysurvey.org/viewer-desi/?ra=55.1092&dec=-28.6770&layer=ls-dr9&zoom=15&sga&sga-parent

**Comment by moustakas** [comment]
Some additional missing systems based on a comparison with Hecate:

* PGC070787 - LSB - https://www.legacysurvey.org/viewer-desi?ra=348.643309&dec=-43.603653&layer=ls-dr9&zoom=13&sga-parent&sga#PGC093119 
* [KKH2007]J1228+4358 - very LSB (probably real) - https://www.legacysurvey.org/viewer-desi?ra=187.183803&dec=43.973394&layer=ls-dr9&zoom=14&sga-parent&sga#PGC093119
* UGC08614 - blatantly missing; in the parent sample but gone from the SGA?? - https://www.legacysurvey.org/viewer-desi?ra=187.183803&dec=43.973394&layer=ls-dr9&zoom=14&sga-parent&sga#UGC08614
* GARLAND=PGC029167 - tidal dwarf from previous NGC3077-M81 interaction; ambiguous whether it should be included in the SGA, but it could be treated as a well-resolved Local-Group dwarf
  * https://ui.adsabs.harvard.edu/abs/1985MNRAS.217..731K/abstract
  * https://www.legacysurvey.org/viewer-desi?ra=150.9646&dec=68.6900&layer=ls-dr9&zoom=12&sga-parent&sga
* IKN - very LSB dwarf spheroidal - 
  * https://www.legacysurvey.org/viewer-desi?ra=152.024775&dec=68.399261&layer=ls-dr9&zoom=12&sga-parent&sga
  * https://link.springer.com/article/10.1134/S1063772919070084
* PGC012798 - blatantly missing; in the parent sample but gone from the SGA?? - https://www.legacysurvey.org/viewer-desi?ra=51.3458&dec=-16.2331&layer=ls-dr9&zoom=13&sga-parent&sga
* PGC166095 - extreme LSB - https://www.legacysurvey.org/viewer-desi?ra=133.199166&dec=33.792528&layer=ls-dr9&zoom=13&sga-parent&sga#PGC166095
* PGC3097827 - extreme LSB(?) - Not sure if this is real. It's in the Karachentsev+2004 catalog (https://leda.univ-lyon1.fr/fG.cgi?n=a115&o=PGC3097827) but it looks like Galactic cirrus to me--
  * https://www.legacysurvey.org/viewer-desi?ra=146.19625&dec=67.438611&layer=ls-dr9&zoom=12&sga-parent&sga#PGC018515
* PGC040869 - LSB - https://www.legacysurvey.org/viewer-desi?ra=186.8826&dec=9.5958&layer=ls-dr9&zoom=14&sga-parent&sga#PGC018515
* PGC043697 - LSB but we really should have included it - https://www.legacysurvey.org/viewer-desi?ra=193.1516&dec=-6.289763&layer=ls-dr9&zoom=14&sga-parent&sga#PGC018515
* PGC061664 - real merger - https://www.legacysurvey.org/viewer-desi?ra=274.0394&dec=42.6564&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC028759=Arp's Loop - resolved, low-mass galaxy 
  * https://www.legacysurvey.org/viewer-desi?ra=149.378351&dec=69.277706&layer=ls-dr9&zoom=12&sga-parent&sga
  * https://leda.univ-lyon1.fr/fG.cgi?n=a115&o=PGC028759
* PGC012345 - blatantly missing - https://www.legacysurvey.org/viewer-desi?ra=49.7367&dec=-10.5464&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC001575 - blatantly missing - https://www.legacysurvey.org/viewer-desi?ra=6.37335&dec=-14.553&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC2807106 - blatantly missing - https://www.legacysurvey.org/viewer-desi?ra=34.461744&dec=6.307257&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC014377 - blatantly missing - https://www.legacysurvey.org/viewer-desi?ra=60.893025&dec=-17.198249&layer=ls-dr9&zoom=14&sga-parent&sga
* UGC12515 - buried in a bright star, but real - https://www.legacysurvey.org/viewer-desi?ra=349.963097&dec=26.262785&layer=ls-dr9&zoom=14&sga-parent&sga
* UGCA342=PGC046093 - resolved (tidal?) dwarf - https://www.legacysurvey.org/viewer-desi?ra=198.777915&dec=42.001381&layer=ls-dr9&zoom=14&sga-parent&sga#PGC046093
* [HS98]117 - LSB - https://www.legacysurvey.org/viewer-desi?ra=155.354967&dec=71.11615&layer=ls-dr9&zoom=14&sga-parent&sga#PGC046093
* KKH089 - resolved dwarf? real?
  * https://www.legacysurvey.org/viewer-desi?ra=155.354967&dec=71.11615&layer=ls-dr9&zoom=14&sga-parent&sga#PGC046093
  * https://leda.univ-lyon1.fr/ledacat.cgi?o=KKH089
  * https://www.legacysurvey.org/viewer-desi?ra=278.184261&dec=33.387974&layer=ls-dr9&zoom=14&sga-parent&sga#PGC046093
* ESO290-051 - blatantly missing (as well as some other neighbors) - https://www.legacysurvey.org/viewer-desi?ra=346.733217&dec=-42.898583&layer=ls-dr9&zoom=14&sga-parent&sga#PGC046093
* 2MASXJ21080727-1001115 - blatantly missing (lots of surrounding cirrus) - https://www.legacysurvey.org/viewer-desi?ra=317.03026&dec=-10.019898&layer=ls-dr9&zoom=14&sga-parent&sga#PGC046093
* UGC07242 - real but adjacent to a very bright star - https://www.legacysurvey.org/viewer-desi?ra=183.535027&dec=66.094687&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* PGC044422 - blatantly missing - https://www.legacysurvey.org/viewer-desi?ra=194.555466&dec=28.948121&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* [KKH2007]J1243+4127 - LSB - https://www.legacysurvey.org/viewer-desi?ra=190.979964&dec=41.456878&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* AGC238914 - lower SB, but not sure why we missing this - https://www.legacysurvey.org/viewer-desi?ra=208.969585&dec=30.348889&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* AGC335954 - lower SB - https://www.legacysurvey.org/viewer-desi?ra=349.445409&dec=21.099168&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* AGC102755 - lower SB - https://www.legacysurvey.org/viewer-desi?ra=4.122918&dec=30.955&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* 2MASXJ20555189-0344142 - blatant - https://www.legacysurvey.org/viewer-desi?ra=313.966275&dec=-3.73731&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* PGC040819 - LSB + star; in parent catalog but dropped from SGA (why??) - https://www.legacysurvey.org/viewer-desi?ra=186.823911&dec=14.147368&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* PGC006518 - blatant - https://www.legacysurvey.org/viewer-desi?ra=26.663431&dec=-3.780192&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* 2MASXJ10113491+6915290 - blatant - https://www.legacysurvey.org/viewer-desi?ra=152.89539&dec=69.258085&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* AGC103619 - blatant - https://www.legacysurvey.org/viewer-desi?ra=3.962082&dec=8.401389&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* SDSSJ215817.93-025404.8 - real but embedded in cirrus - https://www.legacysurvey.org/viewer-desi?ra=329.574708&dec=-2.901333&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* PGC2807105 - real but coordinates aren't great - https://www.legacysurvey.org/viewer-desi?ra=33.113812&dec=10.332834&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* PGC023521 - dwarf - https://www.legacysurvey.org/viewer-desi?ra=125.981338&dec=71.030825&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* 2MASXJ13051021-0450129 - blatant - https://www.legacysurvey.org/viewer-desi?ra=196.292504&dec=-4.83684&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* SDSSJ102727.68+231812.2 - real but coordinates are very poor - https://www.legacysurvey.org/viewer-desi?ra=156.865352&dec=23.303375&layer=ls-dr9&zoom=14&sga-parent&sga#UGC07242
* UGC02027 - in parent but dropped from SGA?? - https://www.legacysurvey.org/viewer-desi?ra=38.290077&dec=8.909187&layer=ls-dr9&zoom=14&sga-parent&sga
* AGC193782 - nice - https://www.legacysurvey.org/viewer-desi?ra=145.757746&dec=9.252611&layer=ls-dr9&zoom=14&sga-parent&sga
* 2MASXJ20005660-5537536 - blatant - https://www.legacysurvey.org/viewer-desi?ra=300.235771&dec=-55.631569&layer=ls-dr9&zoom=14&sga-parent&sga
* ESO540-032 - LSB - https://www.legacysurvey.org/viewer-desi?ra=12.602349&dec=-19.906444&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC095601 - totally wrong coordinates; LSB - https://www.legacysurvey.org/viewer-desi?ra=127.2684&dec=78.836502&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC057559 - blatant - https://www.legacysurvey.org/viewer-desi?ra=243.509607&dec=28.4969&layer=ls-dr9&zoom=14&sga-parent&sga
* AGC321639 - dwarf - https://www.legacysurvey.org/viewer-desi?ra=340.962091&dec=4.735279&layer=ls-dr9&zoom=14&sga-parent&sga
* PGC087262 - dwarf - https://www.legacysurvey.org/viewer-desi?ra=213.842766&dec=14.250352&layer=ls-dr9&zoom=14&sga-parent&sga
* AGC219464 - dwarf - https://www.legacysurvey.org/viewer-desi?ra=169.551667&dec=16.526111&layer=ls-dr9&zoom=14&sga-parent&sga

**Comment by moustakas** [comment]
The central coordinates for NGC4395 (https://www.legacysurvey.org/viewer-dev/?ra=186.455993&dec=33.546294&layer=ls-dr9&zoom=15&sga&sga-parent)
and NGC0247 (https://www.legacysurvey.org/viewer-dev/?ra=11.783689&dec=-20.758056&layer=ls-dr9&zoom=15&sga&sga-parent#NGC%20247), two large, famous galaxies, are incorrect. Bummer.

**Comment by Snell1185** [comment]
[PGC060073](http://leda.univ-lyon1.fr/ledacat.cgi?o=PGC60073) should not exist
https://www.legacysurvey.org/viewer?ra=259.8425&dec=49.0338&layer=ls-dr10-grz&zoom=16&sga-parent&sga

**Comment by Snell1185** [comment]
[PGC033423](http://leda.univ-lyon1.fr/ledacat.cgi?o=PGC33423) missing the companion
https://www.legacysurvey.org/viewer?ra=165.9745&dec=40.8500&layer=ls-dr10-grz&zoom=15&sga-parent&sga

**Comment by Snell1185** [comment]
https://github.com/moustakas/SGA/issues/56#issuecomment-1587155935 reply

Other examples include: [NGC0598](https://www.legacysurvey.org//viewer/?ra=23.4612&dec=30.6593&layer=ls-dr10-grz&zoom=16&sga-parent&sga) [NGC3031](https://www.legacysurvey.org//viewer/?ra=148.8891&dec=69.0651&layer=ls-dr10-grz&zoom=15&sga-parent&sga) [NGC4258](https://www.legacysurvey.org//viewer/?ra=184.7400&dec=47.3040&layer=ls-dr10-grz&zoom=16&sga-parent&sga) [NGC4826](https://www.legacysurvey.org//viewer/?ra=194.1810&dec=21.6820&layer=ls-dr10-grz&zoom=16&sga-parent&sga) 

These should follow the central artifact is the right position center

**Comment by moustakas** [comment]
The residual masking is too aggressive in some spheroidals, leading to a loss of light in the outer envelopes. A couple examples:
https://sga.legacysurvey.org/group/UGC07124?index=2
https://sga.legacysurvey.org/group/IC0941?index=4

**Comment by moustakas** [comment]
I'm closing this ticket in favor of several new, more finely grained tickets:
* #48
* #51 
* #68 
* #70 
* #73

@Snell1185 thank you for your contributions, which we continue to welcome!

**Comment by Snell1185** [comment]
[PGC213712](http://leda.univ-lyon1.fr/ledacat.cgi?o=PGC213712) is star
