### ISSUE TITLE
Weird short bright strip

### ISSUE THREAD

**Issue by siyue** [moustakas/SGA#58]
A few galaxies (I have checked 400+ galaxies) have a weird bright strip across the galaxy. For example, check the center of [https://portal.nersc.gov/project/cosmo/data/sga/2020/data/334/ESO108-023/ESO108-023-largegalaxy-image-grz.jpg](url). May I ask are they cosmic ray? It there any way to remove them?

**Comment by dstndstn** [comment]
If you mean that bright green line, yes, that's a cosmic ray.  In the centers of galaxies where there is a lot of background light, it is harder to detect and mask cosmic rays.

**Comment by siyue** [comment]
Thanks!

**Comment by moustakas** [comment]
Here's the direct link for ESO108-023
https://www.legacysurvey.org/viewer?ra=334.1342&dec=-64.3893&layer=ls-dr9&zoom=14&sga

Unfortunately, this is more of a CP-reduction issue than an SGA issue, so I'm closing.

**Comment by dstndstn** [comment]
We could in principle try to tune the outlier-detection code to catch these cases where cosmics are harder to catch on top of big galaxies.
