### ISSUE TITLE
DR10 failing bricks related to SGA galaxies

### ISSUE THREAD

**Issue by arjundey** [moustakas/SGA#60]
Dustin has been trying to process the last few hundred bricks for DR10, and I did a quick pass through the brick images which he generated to see what was up. There are a small number of large galaxies and star clusters that are causing failures, and I summarize them below. Could you take a quick look at the list below and the fits to see why these are producing issues for tractor runs? 

Also, there are at least three additions to our masks for star clusters and PNe as well (Phoenix dwarf galaxy, Arp 2, and ESO 28-19). I have listed my very rough guess at the mask location and radius (for circular masks) for these three. 

Here’s my summary of checking the locations on the DR10-early viewer:

Big Galaxies:

NGC 55 + IC1537 - SGA ellipse is not big enough and misses fluxes, not in Star Cluster list
NGC253 - SGA ellipse not big enough, not in Star Cluster list
NGC300 - SGA ellipse looks ok, not in Star Cluster list
Phoenix Dwarf Galaxy - SGA looks OK, not in Star Cluster list. Should we add a “Star Cluster" mask at position RA=27.779507, DEC=-44.446111, Radius=4 arcmin?
NGC4406 + NGC4402 - SGA ellipses look small, not in Star Cluster list
NGC4472 - SGA ellipse looks small, not in Star Cluster list
NGC5236 - not in SGA, not in Star Cluster list
IC5152 - SGA ellipse looks ok but wrong axis ratio, not in Star Cluster list

Star Clusters:

NGC104 - not in SGA,  in Star Cluster list, but crowded field with incomplete coverage; Near SMC
NGC121 -  not in SGA,  in Star Cluster list, but crowded field with incomplete coverage; Near SMC
NGC5139 - not in SGA, in Star Cluster list, in a single isolated DECam pointing - drop!
NGC6752 - not in SGA, in Star Cluster list, in a crowded field
Arp 2 - not in SGA, not in Star Cluster list. Perhaps add a mask at position ra=292.1836 dec=-30.3529 radius=3 arcmin (https://www.legacysurvey.org/viewer?ra=292.1836&dec=-30.3529&layer=ls-dr10-early&zoom=13&sga&GCs-PNe)
ESO 28-19 - not in SGA, not in Star Cluster list. Perhaps add a mask at position ra=6.1922&dec=-72.7938 radius=100 arcsec (https://www.legacysurvey.org/viewer?ra=6.1922&dec=-72.7938&layer=ls-dr10-early&zoom=12&sga&GCs-PNe)

**Comment by moustakas** [comment]
DR10 shipped, but some of the identified systems will come back to haunt us in DR11. Let's track these specific issues in
https://github.com/legacysurvey/legacypipe/issues/724 and #71. Closing here.
