### ISSUE TITLE
[G,R,Z]_COG_PARAMS_MTOT

### ISSUE THREAD

**Issue by manupu** [moustakas/SGA#62]
In light of what is written in https://www.legacysurvey.org/sga/sga2020/#known-issues (third item), I can't figure out if the total magnitudes [G,R,Z]_COG_PARAMS_MTOT are correct and can be used; if this is not the case, I would like to get some suggestions to obtain the total magnitudes for SGA galaxies in the r-band, at least.
Thank you very much

**Comment by moustakas** [comment]
Hi @manupu thanks for posting a ticket. The asymptotic (total) r-band magnitudes *should* be OK although I'm not aware of many tests / comparisons of the derived values compared to previous or independent measurements. (The bug you point to affected the pixel-level curves of growth but I ended up fitting a curve-of-growth model to the cumulative fluxes measured in a handful of apertures, which should be OK.) Also keep in mind that the ellipse-fitting may not be great in crowded fields, so it'd be worth inspecting some of the surface-brightness profiles.

Let me know if this answers your question and, if so, feel free to close this ticket or to follow-up with any other questions.

**Comment by manupu** [comment]
thank you very much
