### ISSUE TITLE
Galaxies that are large enough to be in the SGA, but not in the SGA and SGA-parent catalogs, but could be added by the next SGA release

### ISSUE THREAD

**Issue by Snell1185** [moustakas/SGA#67]
000
[2MASXJ00000256+0817537](https://www.legacysurvey.org/viewer?ra=0.0106&dec=8.2980&layer=ls-dr10-grz&zoom=15)
[2MASXJ00000896+0817338](https://www.legacysurvey.org/viewer?ra=0.0373&dec=8.2927&layer=ls-dr10-grz&zoom=15)
[2MASXJ00003907-4938479](https://www.legacysurvey.org/viewer?ra=0.1627&dec=-49.6467&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[2MASXJ00012299+1616006](https://www.legacysurvey.org/viewer?ra=0.3458&dec=16.2668&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[2MASXJ00015588-5601462](https://www.legacysurvey.org/viewer?ra=0.4825&dec=-56.0294&layer=ls-dr10-grz&zoom=13&sga-parent&sga)
[2MASXJ00022265-4400208](https://www.legacysurvey.org/viewer?ra=0.5943&dec=-44.0061&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[2MASXJ00024550-2958505](https://www.legacysurvey.org/viewer?ra=0.6893&dec=-29.9806&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[AGC102729](https://www.legacysurvey.org/viewer?ra=0.1338&dec=30.8696&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[AGC103583](https://www.legacysurvey.org/viewer?ra=0.4852&dec=9.8888&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[AGC104212](https://www.legacysurvey.org/viewer?ra=0.9604&dec=33.6556&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[AGC104229](https://www.legacysurvey.org/viewer?ra=0.8340&dec=32.5124&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[AGC104679](https://www.legacysurvey.org/viewer?ra=0.7447&dec=20.3868&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[AGC104769](https://www.legacysurvey.org/viewer?ra=0.7442&dec=20.3863&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[AGC103585](https://www.legacysurvey.org/viewer?ra=0.5735&dec=8.9547&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0001m315-6306](https://www.legacysurvey.org/viewer?ra=0.2534&dec=-31.3779&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0001m365-1293](https://www.legacysurvey.org/viewer?ra=0.0414&dec=-36.5683&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0001m392-13376](https://www.legacysurvey.org/viewer?ra=0.2765&dec=-39.1254&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[DR10-0001m405-3541](https://www.legacysurvey.org/viewer?ra=0.0850&dec=-40.4098&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[DR10-0002m572-11149](https://www.legacysurvey.org/viewer?ra=0.3753&dec=-57.2099&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[DR10-0003p102-3276](https://www.legacysurvey.org/viewer?ra=0.4419&dec=10.2390&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0003p155-4645](https://www.legacysurvey.org/viewer?ra=0.5160&dec=15.4067&layer=ls-dr10-grz&zoom=16&sga-parent&sga)
[DR10-0004m402-5555](https://www.legacysurvey.org/viewer?ra=0.4388&dec=-40.1535&layer=ls-dr10-grz&zoom=16&sources-dr10&sga-parent&sga)
[DR10-0004m725-1474](https://www.legacysurvey.org/viewer?ra=0.1100&dec=-72.4585&layer=ls-dr10-grz&zoom=13&sga-parent&sga)
[DR10-0004p210-4457](https://www.legacysurvey.org/viewer?ra=0.4999&dec=20.9807&layer=ls-dr10-grz&zoom=14&sga-parent&sga) Maybe PGC1640217, positioned on the star between the galaxies)
[DR10-0004p262-743](https://www.legacysurvey.org/viewer?ra=0.3213&dec=26.3320&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0004p280-2112](https://www.legacysurvey.org/viewer?ra=0.4066&dec=28.0799&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0004p340-3907](https://www.legacysurvey.org/viewer?ra=0.5887&dec=34.0684&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0004p342-1051](https://www.legacysurvey.org/viewer?ra=0.4997&dec=34.1748&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[DR10-0005m477-1605](https://www.legacysurvey.org/viewer?ra=0.4231&dec=-47.8649&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[DR10-0005m487-1213](https://www.legacysurvey.org/viewer?ra=0.4228&dec=-48.7148&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[DR10-0006p085-1442](https://www.legacysurvey.org/viewer?ra=0.5716&dec=8.4652&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0006p162-5501](https://www.legacysurvey.org/viewer?ra=0.7788&dec=16.3085&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0006p165-3306](https://www.legacysurvey.org/viewer?ra=0.7041&dec=16.5963&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0006p167-2191](https://www.legacysurvey.org/viewer?ra=0.6329&dec=16.7048&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0006p167-3784](https://www.legacysurvey.org/viewer?ra=0.7105&dec=16.6287&layer=ls-dr10-grz&zoom=16&sga-parent&sga)
[DR10-0007m300-2096](https://www.legacysurvey.org/viewer?ra=0.6646&dec=-29.9662&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0007m360-5386](https://www.legacysurvey.org/viewer?ra=0.7826&dec=-35.9249&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0007m360-8600](https://www.legacysurvey.org/viewer?ra=0.8859&dec=-35.9303&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0008p037-1072](https://www.legacysurvey.org/viewer?ra=0.7800&dec=3.6835&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0008p040-1420](https://www.legacysurvey.org/viewer?ra=0.7899&dec=3.9846&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[DR10-0009p162-1712](https://www.legacysurvey.org/viewer?ra=0.8508&dec=16.1876&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC000026](https://www.legacysurvey.org/viewer?ra=0.1150&dec=-7.8823&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC000057](https://www.legacysurvey.org/viewer?ra=0.1765&dec=28.3691&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC000067](https://www.legacysurvey.org/viewer?ra=0.2341&dec=-49.5213&layer=ls-dr10-grz&zoom=13&sga-parent&sga)
[PGC000097](https://www.legacysurvey.org/viewer?ra=0.3729&dec=13.0984&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC000169](https://www.legacysurvey.org/viewer?ra=0.6160&dec=-7.6888&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC000198](https://www.legacysurvey.org/viewer?ra=0.7356&dec=29.5831&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC087685](https://www.legacysurvey.org/viewer?ra=0.6832&dec=-35.9293&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC087691](https://www.legacysurvey.org/viewer?ra=0.7419&dec=-35.7978&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC124799](https://www.legacysurvey.org/viewer?ra=0.1787&dec=-39.4361&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC124807](https://www.legacysurvey.org/viewer?ra=0.3014&dec=-39.2311&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC124818](https://www.legacysurvey.org/viewer?ra=0.5306&dec=-38.5364&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC138064](https://www.legacysurvey.org/viewer?ra=0.7013&dec=18.9696&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC138068](https://www.legacysurvey.org/viewer?ra=0.7794&dec=-35.9082&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC138069](https://www.legacysurvey.org/viewer?ra=0.7796&dec=-35.9410&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC138072](https://www.legacysurvey.org/viewer?ra=0.8387&dec=-35.9393&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC138073](https://www.legacysurvey.org/viewer?ra=0.8587&dec=-35.8897&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC143237](https://www.legacysurvey.org/viewer?ra=0.8541&dec=-48.9582&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC165292](https://www.legacysurvey.org/viewer?ra=0.8106&dec=32.8499&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC170488](https://www.legacysurvey.org/viewer?ra=0.9928&dec=-67.7843&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC224000](https://www.legacysurvey.org/viewer?ra=0.5981&dec=-82.1388&layer=ls-dr10-grz&zoom=12&sga-parent&sga)
[PGC435325](https://www.legacysurvey.org/viewer?ra=0.9873&dec=-53.0182&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC463676](https://www.legacysurvey.org/viewer?ra=0.4703&dec=-50.7193&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC482690](https://www.legacysurvey.org/viewer?ra=0.7861&dec=-48.8850&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC486850](https://www.legacysurvey.org/viewer?ra=0.9430&dec=-48.4945&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC495308](https://www.legacysurvey.org/viewer?ra=0.3116&dec=-47.8141&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC495312](https://www.legacysurvey.org/viewer?ra=0.2721&dec=-47.8137&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC508513](https://www.legacysurvey.org/viewer?ra=0.1935&dec=-46.9581&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC517082](https://www.legacysurvey.org/viewer?ra=0.4871&dec=-46.2599&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC543344](https://www.legacysurvey.org/viewer?ra=0.3807&dec=-43.8868&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC543678](https://www.legacysurvey.org/viewer?ra=0.4003&dec=-43.8606&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC543837](https://www.legacysurvey.org/viewer?ra=0.5322&dec=-43.8487&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC544058](https://www.legacysurvey.org/viewer?ra=0.8274&dec=-43.8328&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC616134](https://www.legacysurvey.org/viewer?ra=0.1669&dec=-37.6938&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC618004](https://www.legacysurvey.org/viewer?ra=0.1584&dec=-37.7653&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC624565](https://www.legacysurvey.org/viewer?ra=0.7536&dec=-37.3535&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC644912](https://www.legacysurvey.org/viewer?ra=0.8014&dec=-35.7606&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC657978](https://www.legacysurvey.org/viewer?ra=0.8688&dec=-34.7548&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC662139](https://www.legacysurvey.org/viewer?ra=0.8357&dec=-34.4504&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC783590](https://www.legacysurvey.org/viewer?ra=0.2420&dec=-25.0141&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC1015177](https://www.legacysurvey.org/viewer?ra=0.5814&dec=-7.6681&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC1217772](https://www.legacysurvey.org/viewer?ra=0.8115&dec=2.1562&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC1345535](https://www.legacysurvey.org/viewer?ra=0.6218&dec=8.3693&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC1368798](https://www.legacysurvey.org/viewer?ra=0.7135&dec=9.7018&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC1377873](https://www.legacysurvey.org/viewer?ra=0.9236&dec=10.3479&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC1601562](https://www.legacysurvey.org/viewer?ra=0.5670&dec=19.6798&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC1807476](https://www.legacysurvey.org/viewer?ra=0.3900&dec=27.4002&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC1814250](https://www.legacysurvey.org/viewer?ra=0.1731&dec=27.6514&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC2025468](https://www.legacysurvey.org/viewer?ra=0.7598&dec=33.1758&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC2799417](https://www.legacysurvey.org/viewer?ra=0.6779&dec=-34.6600&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC2799425](https://www.legacysurvey.org/viewer?ra=0.8496&dec=-34.6092&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC3089842](https://www.legacysurvey.org/viewer?ra=0.4119&dec=22.3625&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC3092239](https://www.legacysurvey.org/viewer?ra=0.8894&dec=3.6131&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC3092239](https://www.legacysurvey.org/viewer?ra=0.8895&dec=3.6133&layer=ls-dr10-grz&zoom=15&sga-parent&sga)
[PGC3587733](https://www.legacysurvey.org/viewer?ra=0.4408&dec=-76.9541&layer=ls-dr10-grz&zoom=12&sga-parent&sga)
[PGC3587911](https://www.legacysurvey.org/viewer?ra=0.5667&dec=-3.2332&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC3588071](https://www.legacysurvey.org/viewer?ra=0.6854&dec=-29.9111&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[PGC3588375](https://www.legacysurvey.org/viewer?ra=0.8861&dec=-80.3611&layer=ls-dr10-grz&zoom=12&sga-parent&sga)
[WINGSJ000154.36-360613.7](https://www.legacysurvey.org/viewer?ra=0.4770&dec=-36.1042&layer=ls-dr10-grz&zoom=14&sga-parent&sga)
[WINGSJ000348.28-355900.2](https://www.legacysurvey.org/viewer?ra=0.9510&dec=-35.9835&layer=ls-dr10-grz&zoom=15&sga-parent&sga)

**Comment by moustakas** [comment]
@Snell1185 thank you for these contributions. I've moved this list over to https://github.com/moustakas/SGA/issues/73; let's continue the cataloging there.
