### ISSUE TITLE
SGA and LEDA links incorrect, should be used by objname instead

### ISSUE THREAD

**Issue by TriShotFlurry** [moustakas/SGA#79]
@moustakas 
The links to the objects are connected by the PGC number and not the designation. The PGC in these galaxies are set up entirely wrong especially affecting the galaxies with the designation as SDSS or 2MASX identifier, which displays an error. Try changing the link properties from name only.

**Comment by dstndstn** [comment]
Hi,
If you're talking about a web page, PLEASE include a link to an example web page with the problem.
Then, say what the link currently is, and what the link should be instead.
Thanks,
dustin

**Comment by TriShotFlurry** [comment]
Hi Dustin, sorry for the late reply, the notifications refuse to pop up on me! 😣

I have investigated a few SGA-2020 galaxies and their links were incorrectly set to pgc, and LEDA does not support search. Please change that link search to objname for it to work correctly.
http://leda.univ-lyon1.fr/ledacat.cgi?o=PGC4334605 should be http://leda.univ-lyon1.fr/ledacat.cgi?o=SDSSJ123726.79+260435.5

**Comment by dstndstn** [comment]
Done in https://github.com/legacysurvey/imagine/commit/8afe16231b09d67a98e2a0c74a6f7464e9b3bc6a

**Comment by dstndstn** [comment]
@TriShotFlurry can you please check that this fixes the problem you're reporting, and that it doesn't mess up other ones?
thanks.

**Comment by TriShotFlurry** [comment]
Seems to work like a charm. Thanks!
